version: '3.4'

services:
  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - fullstack-sqldata:/var/opt/mssql

  fullstack.mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionString=${FULLSTACK_DB:-Server=sqldata;Database=FullStack.Db;User Id=sa;Password=Pass@word}
    ports:
      - "5002:80"
      - "4432:443"
    
  fullstack.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionString=${FULLSTACK_DB:-Server=sqldata;Database=FullStack.Db;User Id=sa;Password=Pass@word}
      - WeatherCity=Madrid
      - WeatherApiKey=cefcfdc0f8633367e91eb557e578ca08
    ports:
      - "5001:80"
      - "4431:443"

volumes:
  fullstack-sqldata:
    external: false

