version: '3.4'

services:
  redis:
    image: bitnami/redis:latest

  sqldata-api:
    image: mcr.microsoft.com/mssql/server:2019-latest

  sqldata-mvc:
    image: mcr.microsoft.com/mssql/server:2019-latest

  fullstack.mvc:
    image: ${DOCKER_REGISTRY-}fullstackmvc
    build:
      context: .
      dockerfile: FullStack.MVC/Dockerfile
    depends_on:
      - sqldata-mvc

  fullstack.api:
    image: ${DOCKER_REGISTRY-}fullstackapi
    build:
      context: .
      dockerfile: FullStack.API/Dockerfile
    depends_on:
      - sqldata-api

  fullstack.webstatus:
    image: ${DOCKER_REGISTRY-}fullstackwebstatus
    build:
      context: .
      dockerfile: FullStack.WebStatus/Dockerfile

