version: '3.4'

services:
  redis:
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  sqldata-api:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - fullstack-sqldata-api:/var/opt/mssql

  sqldata-mvc:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
    volumes:
      - fullstack-sqldata-mvc:/var/opt/mssql

  fullstack.mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/docker.pfx
      - ConnectionString=${FULLSTACK_DB:-Server=sqldata-mvc;Database=FullStack.Db;User Id=sa;Password=Pass@word}
      - DBConnectionRetries=5
      - ApiUri=http://fullstack.api:80/api/v1
    ports:
      - "5002:80"
      - "4432:443"
    
  fullstack.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/docker.pfx
      - ConnectionString=${FULLSTACK_DB:-Server=sqldata-api;Database=FullStack.Db;User Id=sa;Password=Pass@word}
      - RedisConnectionsString=redis
      - DBConnectionRetries=5
      - WeatherCity=Madrid
      - WeatherApiKey=cefcfdc0f8633367e91eb557e578ca08
    ports:
      - "5001:80"

  fullstack.webstatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/docker.pfx
      - HealthChecksUI__HealthChecks__0__Name=WebMVC HTTP Check
      - HealthChecksUI__HealthChecks__0__Uri=http://fullstack.mvc:80/hc
      - HealthChecksUI__HealthChecks__1__Name=WebAPI HTTP Check
      - HealthChecksUI__HealthChecks__1__Uri=http://fullstack.api:80/hc
      - HealthChecksRefreshTime=15
    ports:
      - "5003:80"

volumes:
  fullstack-sqldata-api:
    external: false
  fullstack-sqldata-mvc:
    external: false
